version: '3'

services:
  mainserver:
    build:
      context: .
      dockerfile: ./src/engine/docker/Dockerfile.main-server
    ports:
      - 3000:3000
    networks:
      - lynx-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

networks:
  lynx-network:
    driver: bridge
